### ISSUE TITLE
Flex grid

### ISSUE THREAD

**Issue by tbb2** [Novicell/novicell-frontend#51] opened 2016-08-30 11:22 UTC
Skal vi ikke lave vores "bootstrap"-grid om til at køre med flex-box!?

**Comment by Dan9boi** [comment] 2016-08-30 14:25
We just had this talk, please see The following link:
https://github.com/Novicell/novicell-frontend/issues/40

**Comment by hesselberg** [comment] 2016-08-31 09:53
Closing this issue as it's a duplicate of #40

**Closed by hesselberg** 2016-08-31 09:53 UTC
Labels: feature, suggestion
